### ISSUE TITLE
[BUG, Android 8.0] Substratum crashes while trying to send the logcat when error in theme install

### ISSUE THREAD

**Issue by Sparker0i** [nicholaschum/substratum#136]
On Android 8.0 Oreo, when there is an error in theme installation, we get a Snackbar at the bottom, with the message 'Target application/overlay outdated or mismatched config..' and the Logchar action. When we click on the Send button, the main app crashes. Tested only with the Flux theme, Not tested with other themes (as they don't give errors)

**Comment by Sparker0i** [comment]
PS. This error does not happen in Android 7.1

**Comment by msfjarvis** [comment]
When you add a [BUG] tag the least you have to do it attach a logcat

**Comment by Sparker0i** [comment]
ok.. I got the logcat now

**Comment by Sparker0i** [comment]
Build version: eight hundred fourty six 
Current date: 2017-09-23 00:56:42 
Device: Xiaomi Redmi Note 3 
 
Stack trace:  
android.os.FileUriExposedException: file:///storage/emulated/0/.substratum/theme_error-20170923-00%3A56.txt exposed beyond app through ClipData.Item.getUri()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
	at android.net.Uri.checkFileUriExposed(Uri.java:2348)
	at android.content.ClipData.prepareToLeaveProcess(ClipData.java:941)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:9735)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:9741)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:9720)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1609)
	at android.app.Activity.startActivityForResult(Activity.java:4472)
	at android.support.v4.a.e.startActivityForResult(Unknown Source:10)
	at android.support.v4.a.i.startActivityForResult(Unknown Source:0)
	at android.app.Activity.startActivityForResult(Activity.java:4430)
	at android.support.v4.a.i.startActivityForResult(Unknown Source:10)
	at android.app.Activity.startActivity(Activity.java:4791)
	at android.app.Activity.startActivity(Activity.java:4759)
	at projekt.substratum.tabs.Overlays$SendErrorReport.onPostExecute(Unknown Source:90)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

User actions: 
2017-09-23 00:49:50: SplashScreenActivity created
2017-09-23 00:49:51: SplashScreenActivity resumed
2017-09-23 00:49:51: SplashScreenActivity paused
2017-09-23 00:49:51: MainActivity created
2017-09-23 00:49:52: MainActivity resumed
2017-09-23 00:49:53: SplashScreenActivity destroyed
2017-09-23 00:50:10: MainActivity paused
2017-09-23 00:50:10: ThemeLaunchActivity created
2017-09-23 00:50:10: ThemeLaunchActivity resumed
2017-09-23 00:50:10: ThemeLaunchActivity paused
2017-09-23 00:50:10: InformationActivity created
2017-09-23 00:50:11: InformationActivity resumed
2017-09-23 00:50:19: InformationActivity paused
2017-09-23 00:50:19: MainActivity resumed
2017-09-23 00:50:19: ThemeLaunchActivity destroyed
2017-09-23 00:50:19: InformationActivity destroyed
2017-09-23 00:50:21: MainActivity paused
2017-09-23 00:50:21: ThemeLaunchActivity created
2017-09-23 00:50:21: ThemeLaunchActivity resumed
2017-09-23 00:50:21: ThemeLaunchActivity paused
2017-09-23 00:50:21: ThemeLaunchActivity resumed
2017-09-23 00:50:21: ThemeLaunchActivity paused
2017-09-23 00:50:21: ThemeLaunchActivity resumed
2017-09-23 00:50:21: ThemeLaunchActivity paused
2017-09-23 00:50:21: InformationActivity created
2017-09-23 00:50:22: InformationActivity resumed
2017-09-23 00:50:23: InformationActivity paused
2017-09-23 00:50:23: MainActivity resumed
2017-09-23 00:50:23: ThemeLaunchActivity destroyed
2017-09-23 00:50:23: InformationActivity destroyed
2017-09-23 00:50:25: MainActivity paused
2017-09-23 00:50:25: ThemeLaunchActivity created
2017-09-23 00:50:25: ThemeLaunchActivity resumed
2017-09-23 00:50:25: ThemeLaunchActivity paused
2017-09-23 00:50:25: InformationActivity created
2017-09-23 00:50:25: InformationActivity resumed
2017-09-23 00:50:35: ThemeLaunchActivity destroyed
2017-09-23 00:51:25: InformationActivity paused
2017-09-23 00:51:25: MainActivity resumed
2017-09-23 00:51:26: InformationActivity destroyed
2017-09-23 00:51:27: MainActivity paused
2017-09-23 00:51:27: ThemeLaunchActivity created
2017-09-23 00:51:27: ThemeLaunchActivity resumed
2017-09-23 00:51:27: ThemeLaunchActivity paused
2017-09-23 00:51:27: InformationActivity created
2017-09-23 00:51:28: InformationActivity resumed
2017-09-23 00:51:37: ThemeLaunchActivity destroyed
2017-09-23 00:52:32: InformationActivity paused
2017-09-23 00:54:11: InformationActivity resumed

**Comment by Sparker0i** [comment]
Build version: eight hundred fourty six 
Current date: 2017-09-23 00:56:42 
Device: Xiaomi Redmi Note 3 
 
Stack trace:  
android.os.FileUriExposedException: file:///storage/emulated/0/.substratum/theme_error-20170923-00%3A56.txt exposed beyond app through ClipData.Item.getUri()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
	at android.net.Uri.checkFileUriExposed(Uri.java:2348)
	at android.content.ClipData.prepareToLeaveProcess(ClipData.java:941)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:9735)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:9741)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:9720)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1609)
	at android.app.Activity.startActivityForResult(Activity.java:4472)
	at android.support.v4.a.e.startActivityForResult(Unknown Source:10)
	at android.support.v4.a.i.startActivityForResult(Unknown Source:0)
	at android.app.Activity.startActivityForResult(Activity.java:4430)
	at android.support.v4.a.i.startActivityForResult(Unknown Source:10)
	at android.app.Activity.startActivity(Activity.java:4791)
	at android.app.Activity.startActivity(Activity.java:4759)
	at projekt.substratum.tabs.Overlays$SendErrorReport.onPostExecute(Unknown Source:90)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

User actions: 
2017-09-23 00:49:50: SplashScreenActivity created
2017-09-23 00:49:51: SplashScreenActivity resumed
2017-09-23 00:49:51: SplashScreenActivity paused
2017-09-23 00:49:51: MainActivity created
2017-09-23 00:49:52: MainActivity resumed
2017-09-23 00:49:53: SplashScreenActivity destroyed
2017-09-23 00:50:10: MainActivity paused
2017-09-23 00:50:10: ThemeLaunchActivity created
2017-09-23 00:50:10: ThemeLaunchActivity resumed
2017-09-23 00:50:10: ThemeLaunchActivity paused
2017-09-23 00:50:10: InformationActivity created
2017-09-23 00:50:11: InformationActivity resumed
2017-09-23 00:50:19: InformationActivity paused
2017-09-23 00:50:19: MainActivity resumed
2017-09-23 00:50:19: ThemeLaunchActivity destroyed
2017-09-23 00:50:19: InformationActivity destroyed
2017-09-23 00:50:21: MainActivity paused
2017-09-23 00:50:21: ThemeLaunchActivity created
2017-09-23 00:50:21: ThemeLaunchActivity resumed
2017-09-23 00:50:21: ThemeLaunchActivity paused
2017-09-23 00:50:21: ThemeLaunchActivity resumed
2017-09-23 00:50:21: ThemeLaunchActivity paused
2017-09-23 00:50:21: ThemeLaunchActivity resumed
2017-09-23 00:50:21: ThemeLaunchActivity paused
2017-09-23 00:50:21: InformationActivity created
2017-09-23 00:50:22: InformationActivity resumed
2017-09-23 00:50:23: InformationActivity paused
2017-09-23 00:50:23: MainActivity resumed
2017-09-23 00:50:23: ThemeLaunchActivity destroyed
2017-09-23 00:50:23: InformationActivity destroyed
2017-09-23 00:50:25: MainActivity paused
2017-09-23 00:50:25: ThemeLaunchActivity created
2017-09-23 00:50:25: ThemeLaunchActivity resumed
2017-09-23 00:50:25: ThemeLaunchActivity paused
2017-09-23 00:50:25: InformationActivity created
2017-09-23 00:50:25: InformationActivity resumed
2017-09-23 00:50:35: ThemeLaunchActivity destroyed
2017-09-23 00:51:25: InformationActivity paused
2017-09-23 00:51:25: MainActivity resumed
2017-09-23 00:51:26: InformationActivity destroyed
2017-09-23 00:51:27: MainActivity paused
2017-09-23 00:51:27: ThemeLaunchActivity created
2017-09-23 00:51:27: ThemeLaunchActivity resumed
2017-09-23 00:51:27: ThemeLaunchActivity paused
2017-09-23 00:51:27: InformationActivity created
2017-09-23 00:51:28: InformationActivity resumed
2017-09-23 00:51:37: ThemeLaunchActivity destroyed
2017-09-23 00:52:32: InformationActivity paused
2017-09-23 00:54:11: InformationActivity resumed

**Comment by Sparker0i** [comment]
Build version: eight hundred fourty six 
Current date: 2017-09-23 00:56:42 
Device: Xiaomi Redmi Note 3 
 
Stack trace:  
android.os.FileUriExposedException: file:///storage/emulated/0/.substratum/theme_error-20170923-00%3A56.txt exposed beyond app through ClipData.Item.getUri()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
	at android.net.Uri.checkFileUriExposed(Uri.java:2348)
	at android.content.ClipData.prepareToLeaveProcess(ClipData.java:941)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:9735)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:9741)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:9720)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1609)
	at android.app.Activity.startActivityForResult(Activity.java:4472)
	at android.support.v4.a.e.startActivityForResult(Unknown Source:10)
	at android.support.v4.a.i.startActivityForResult(Unknown Source:0)
	at android.app.Activity.startActivityForResult(Activity.java:4430)
	at android.support.v4.a.i.startActivityForResult(Unknown Source:10)
	at android.app.Activity.startActivity(Activity.java:4791)
	at android.app.Activity.startActivity(Activity.java:4759)
	at projekt.substratum.tabs.Overlays$SendErrorReport.onPostExecute(Unknown Source:90)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

User actions: 
2017-09-23 00:49:50: SplashScreenActivity created
2017-09-23 00:49:51: SplashScreenActivity resumed
2017-09-23 00:49:51: SplashScreenActivity paused
2017-09-23 00:49:51: MainActivity created
2017-09-23 00:49:52: MainActivity resumed
2017-09-23 00:49:53: SplashScreenActivity destroyed
2017-09-23 00:50:10: MainActivity paused
2017-09-23 00:50:10: ThemeLaunchActivity created
2017-09-23 00:50:10: ThemeLaunchActivity resumed
2017-09-23 00:50:10: ThemeLaunchActivity paused
2017-09-23 00:50:10: InformationActivity created
2017-09-23 00:50:11: InformationActivity resumed
2017-09-23 00:50:19: InformationActivity paused
2017-09-23 00:50:19: MainActivity resumed
2017-09-23 00:50:19: ThemeLaunchActivity destroyed
2017-09-23 00:50:19: InformationActivity destroyed
2017-09-23 00:50:21: MainActivity paused
2017-09-23 00:50:21: ThemeLaunchActivity created
2017-09-23 00:50:21: ThemeLaunchActivity resumed
2017-09-23 00:50:21: ThemeLaunchActivity paused
2017-09-23 00:50:21: ThemeLaunchActivity resumed
2017-09-23 00:50:21: ThemeLaunchActivity paused
2017-09-23 00:50:21: ThemeLaunchActivity resumed
2017-09-23 00:50:21: ThemeLaunchActivity paused
2017-09-23 00:50:21: InformationActivity created
2017-09-23 00:50:22: InformationActivity resumed
2017-09-23 00:50:23: InformationActivity paused
2017-09-23 00:50:23: MainActivity resumed
2017-09-23 00:50:23: ThemeLaunchActivity destroyed
2017-09-23 00:50:23: InformationActivity destroyed
2017-09-23 00:50:25: MainActivity paused
2017-09-23 00:50:25: ThemeLaunchActivity created
2017-09-23 00:50:25: ThemeLaunchActivity resumed
2017-09-23 00:50:25: ThemeLaunchActivity paused
2017-09-23 00:50:25: InformationActivity created
2017-09-23 00:50:25: InformationActivity resumed
2017-09-23 00:50:35: ThemeLaunchActivity destroyed
2017-09-23 00:51:25: InformationActivity paused
2017-09-23 00:51:25: MainActivity resumed
2017-09-23 00:51:26: InformationActivity destroyed
2017-09-23 00:51:27: MainActivity paused
2017-09-23 00:51:27: ThemeLaunchActivity created
2017-09-23 00:51:27: ThemeLaunchActivity resumed
2017-09-23 00:51:27: ThemeLaunchActivity paused
2017-09-23 00:51:27: InformationActivity created
2017-09-23 00:51:28: InformationActivity resumed
2017-09-23 00:51:37: ThemeLaunchActivity destroyed
2017-09-23 00:52:32: InformationActivity paused
2017-09-23 00:54:11: InformationActivity resumed

**Comment by Sparker0i** [comment]
Build version: eight hundred fourty six 
Current date: 2017-09-23 00:56:42 
Device: Xiaomi Redmi Note 3 
 
Stack trace:  
android.os.FileUriExposedException: file:///storage/emulated/0/.substratum/theme_error-20170923-00%3A56.txt exposed beyond app through ClipData.Item.getUri()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
	at android.net.Uri.checkFileUriExposed(Uri.java:2348)
	at android.content.ClipData.prepareToLeaveProcess(ClipData.java:941)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:9735)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:9741)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:9720)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1609)
	at android.app.Activity.startActivityForResult(Activity.java:4472)
	at android.support.v4.a.e.startActivityForResult(Unknown Source:10)
	at android.support.v4.a.i.startActivityForResult(Unknown Source:0)
	at android.app.Activity.startActivityForResult(Activity.java:4430)
	at android.support.v4.a.i.startActivityForResult(Unknown Source:10)
	at android.app.Activity.startActivity(Activity.java:4791)
	at android.app.Activity.startActivity(Activity.java:4759)
	at projekt.substratum.tabs.Overlays$SendErrorReport.onPostExecute(Unknown Source:90)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

User actions: 
2017-09-23 00:49:50: SplashScreenActivity created
2017-09-23 00:49:51: SplashScreenActivity resumed
2017-09-23 00:49:51: SplashScreenActivity paused
2017-09-23 00:49:51: MainActivity created
2017-09-23 00:49:52: MainActivity resumed
2017-09-23 00:49:53: SplashScreenActivity destroyed
2017-09-23 00:50:10: MainActivity paused
2017-09-23 00:50:10: ThemeLaunchActivity created
2017-09-23 00:50:10: ThemeLaunchActivity resumed
2017-09-23 00:50:10: ThemeLaunchActivity paused
2017-09-23 00:50:10: InformationActivity created
2017-09-23 00:50:11: InformationActivity resumed
2017-09-23 00:50:19: InformationActivity paused
2017-09-23 00:50:19: MainActivity resumed
2017-09-23 00:50:19: ThemeLaunchActivity destroyed
2017-09-23 00:50:19: InformationActivity destroyed
2017-09-23 00:50:21: MainActivity paused
2017-09-23 00:50:21: ThemeLaunchActivity created
2017-09-23 00:50:21: ThemeLaunchActivity resumed
2017-09-23 00:50:21: ThemeLaunchActivity paused
2017-09-23 00:50:21: ThemeLaunchActivity resumed
2017-09-23 00:50:21: ThemeLaunchActivity paused
2017-09-23 00:50:21: ThemeLaunchActivity resumed
2017-09-23 00:50:21: ThemeLaunchActivity paused
2017-09-23 00:50:21: InformationActivity created
2017-09-23 00:50:22: InformationActivity resumed
2017-09-23 00:50:23: InformationActivity paused
2017-09-23 00:50:23: MainActivity resumed
2017-09-23 00:50:23: ThemeLaunchActivity destroyed
2017-09-23 00:50:23: InformationActivity destroyed
2017-09-23 00:50:25: MainActivity paused
2017-09-23 00:50:25: ThemeLaunchActivity created
2017-09-23 00:50:25: ThemeLaunchActivity resumed
2017-09-23 00:50:25: ThemeLaunchActivity paused
2017-09-23 00:50:25: InformationActivity created
2017-09-23 00:50:25: InformationActivity resumed
2017-09-23 00:50:35: ThemeLaunchActivity destroyed
2017-09-23 00:51:25: InformationActivity paused
2017-09-23 00:51:25: MainActivity resumed
2017-09-23 00:51:26: InformationActivity destroyed
2017-09-23 00:51:27: MainActivity paused
2017-09-23 00:51:27: ThemeLaunchActivity created
2017-09-23 00:51:27: ThemeLaunchActivity resumed
2017-09-23 00:51:27: ThemeLaunchActivity paused
2017-09-23 00:51:27: InformationActivity created
2017-09-23 00:51:28: InformationActivity resumed
2017-09-23 00:51:37: ThemeLaunchActivity destroyed
2017-09-23 00:52:32: InformationActivity paused
2017-09-23 00:54:11: InformationActivity resumed
resume

**Comment by Sparker0i** [comment]
please check

**Comment by nicholaschum** [comment]
Fixed with 1b54445da329c8189078af70526f71289aa19475
