### ISSUE TITLE
Overlay list crash

### ISSUE THREAD

**Issue by Vladislav-Ilcheff** [nicholaschum/substratum#138]
This is trace from the app itself:
ROM is Viper10 which is Android 7.0 with RRO2 engine
This happens even after reinstalling the app itself with no themes installed.

Build version: eight hundred fifty three 
Current date: 2017-09-26 11:37:16 
Device: HTC 10 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.compareToIgnoreCase(java.lang.String)' on a null object reference
 at projekt.substratum.adapters.fragments.manager.ManagerItem.compareToByTheme(ManagerItem.java:211)
 at projekt.substratum.fragments.ManagerFragment.quicksort(ManagerFragment.java:187)
 at projekt.substratum.fragments.ManagerFragment.access$1100(ManagerFragment.java:87)
 at projekt.substratum.fragments.ManagerFragment$LayoutReloader.onPostExecute(ManagerFragment.java:676)
 at projekt.substratum.fragments.ManagerFragment$LayoutReloader.onPostExecute(ManagerFragment.java:554)
 at android.os.AsyncTask.finish(AsyncTask.java)
 at android.os.AsyncTask.-wrap1(AsyncTask.java)
 at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java)
 at android.os.Handler.dispatchMessage(Handler.java)
 at android.os.Looper.loop(Looper.java)
 at android.app.ActivityThread.main(ActivityThread.java)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)

User actions: 
2017-09-26 11:37:11: LauncherActivity created
2017-09-26 11:37:11: SplashScreenActivity created
2017-09-26 11:37:11: SplashScreenActivity resumed
2017-09-26 11:37:11: SplashScreenActivity paused
2017-09-26 11:37:11: MainActivity created
2017-09-26 11:37:12: MainActivity resumed
2017-09-26 11:37:12: SplashScreenActivity destroyed
2017-09-26 11:37:12: LauncherActivity destroyed

**Comment by msfjarvis** [comment]
This is a known bug and being internally tracked. We'll update this issue when there's progress to share.

**Comment by msfjarvis** [comment]
Fixed via https://github.com/substratum/substratum/commit/adaa07fae056b666fc0817e025da6378c0a18e26
