### ISSUE TITLE
substratum is crashing on my phone

### ISSUE THREAD

**Issue by jmona789** [nicholaschum/substratum#154]
I cannt disable or enable any overlays, everytime I launch substratum it crashes, stack trace:
Build version: nine hundred five
Device: Pixel XL (marlin) [google/marlin/marlin:8.0.0/OPR3.170623.008/4294783:user/release-keys]
ROM: 8.0.0 - Unknown
Theme system: OMS (andromeda)

Stack trace:
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException
	at java.io.File.<init>(File.java:282)
	at projekt.substratum.activities.launch.SplashScreenActivity$CheckSamsung.doInBackground(SplashScreenActivity.java:187)
	at projekt.substratum.activities.launch.SplashScreenActivity$CheckSamsung.doInBackground(SplashScreenActivity.java:113)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

User actions:
2017-11-02 23:52:52: RescueActivity created
2017-11-02 23:52:53: RescueActivity destroyed
2017-11-02 23:57:27: LauncherActivity created
2017-11-02 23:57:27: SplashScreenActivity created
2017-11-02 23:57:28: SplashScreenActivity resumed
2017-11-02 23:57:28: LauncherActivity destroyed

**Comment by nathanchance** [comment]
Does long pressing on the Substratum icon on your launcher and hitting "Rescue Me!" work?

**Comment by jmona789** [comment]
The "Rescue ME!" button did not work, I went into settings and Apps & notifications and tried manually deleting the theme for substratum itself in case that was the issue, but it was still crashing, however I noticed I could access the theme showcase with it crashing, then today at around 11:00 it just starting working again.  Also, thanks for the commit nicholaschum,  it started working earlier today before that commit, but I'm sure that will help people in the future.
