### ISSUE TITLE
Substratum crashes on launch

### ISSUE THREAD

**Issue by incinirate** [nicholaschum/substratum#183]
It has worked fine for months, and all of a sudden it now crashes on launch. I've tried reinstalling, clearing the cache, wiping data, in various combinations, to no effect.
The "rescue me!" and "restart" options do nothing

```Build version: one thousand seven
Device: Moto G (5S) Plus (sanders) [motorola/sanders/sanders:7.1.1/NPSS26.116-48-9/14:user/release-keys]
ROM: 7.1.1 - Unknown
Theme system: RRO (Legacy)

Stack trace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{projekt.substratum/projekt.substratum.activities.launch.SplashScreenActivity}: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2678)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2743)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1490)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6165)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}
at android.content.res.TypedArray.getColorStateList(TypedArray.java:528)
at android.widget.TextView.<init>(TextView.java:783)
at android.widget.TextView.<init>(TextView.java:704)
at android.widget.TextView.<init>(TextView.java:700)
at android.widget.TextView.<init>(TextView.java:696)
at android.widget.Toolbar.setTitle(Toolbar.java:737)
at com.android.internal.widget.ToolbarWidgetWrapper.setTitleInt(ToolbarWidgetWrapper.java:262)
at com.android.internal.widget.ToolbarWidgetWrapper.setWindowTitle(ToolbarWidgetWrapper.java:244)
at com.android.internal.widget.ActionBarOverlayLayout.setWindowTitle(ActionBarOverlayLayout.java:669)
at com.android.internal.policy.PhoneWindow.setTitle(PhoneWindow.java:536)
at com.android.internal.policy.PhoneWindow.setTitle(PhoneWindow.java:529)
at android.app.Activity.onTitleChanged(Activity.java:5672)
at android.app.Activity.onPostCreate(Activity.java:1152)
at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1221)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2660)
... 9 more


User actions:
2018-10-19 00:27:43: LauncherActivity created
2018-10-19 00:27:43: SplashScreenActivity created

```

**Comment by msfjarvis** [comment]
Flash the substratum legacy rescue ZIP in TWRP, you should find it in `/sdcard/substratum/`
