### ISSUE TITLE
Crash while enabling and disabling overlays

### ISSUE THREAD

**Issue by Danielsahm** [nicholaschum/substratum#196]
Build version: one thousand fifteen
Device: SM-N950F (greatlte) [samsung/greatltexx/greatlte:9/PPR1.180610.011/N950FXXS5DSB4:user/release-keys]
ROM: 9 - Unknown
Theme system: Not detected

Stack trace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{projekt.substratum/projekt.substratum.MainActivity}: android.view.InflateException: Binary XML file line #66: Binary XML file line #66: Error inflating class <unknown>
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3108)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3251)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5034)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4943)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:59)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:4993)
	at android.app.ActivityThread.access$3300(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1958)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7045)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
Caused by: android.view.InflateException: Binary XML file line #66: Binary XML file line #66: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #66: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
	at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:303)
	at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284)
	at projekt.substratum.MainActivity.onCreate(MainActivity.java:267)
	at android.app.Activity.performCreate(Activity.java:7327)
	at android.app.Activity.performCreate(Activity.java:7318)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3088)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3251)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5034)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4943)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:59)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:4993)
	at android.app.ActivityThread.access$3300(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1958)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7045)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
Caused by: android.content.res.Resources$NotFoundException: File res/color/bottombar_icon_text_selected.xml from ComplexColor resource ID #0x7f06003d
	at android.content.res.ResourcesImpl.loadComplexColorForCookie(ResourcesImpl.java:1181)
	at android.content.res.ResourcesImpl.loadComplexColorFromName(ResourcesImpl.java:1007)
	at android.content.res.ResourcesImpl.loadColorStateList(ResourcesImpl.java:1086)
	at android.content.res.Resources.getColorStateList(Resources.java:1047)
	at android.content.Context.getColorStateList(Context.java:644)
	at androidx.appcompat.content.res.AppCompatResources.getColorStateList(AppCompatResources.java:67)
	at androidx.appcompat.widget.TintTypedArray.getColorStateList(TintTypedArray.java:171)
	at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:148)
	at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:114)
	... 35 more
Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 0 to color: type=0x1
	at android.content.res.TypedArray.getColor(TypedArray.java:482)
	at android.content.res.ColorStateList.inflate(ColorStateList.java:327)
	at android.content.res.ColorStateList.createFromXmlInner(ColorStateList.java:275)
	at android.content.res.ResourcesImpl.loadComplexColorForCookie(ResourcesImpl.java:1174)
	... 43 more

User actions:
2019-04-03 22:54:25: LauncherActivity created
2019-04-03 22:54:25: SplashScreenActivity created
2019-04-03 22:54:25: SplashScreenActivity resumed
2019-04-03 22:54:26: LauncherActivity destroyed
2019-04-03 22:54:26: SplashScreenActivity paused
2019-04-03 22:54:26: MainActivity created
2019-04-03 22:54:26: MainActivity resumed
2019-04-03 22:54:27: SplashScreenActivity destroyed
2019-04-03 22:54:36: MainActivity paused
2019-04-03 22:54:36: MainActivity resumed
2019-04-03 22:54:44: MainActivity paused
2019-04-03 22:54:53: MainActivity resumed
2019-04-03 22:56:04: MainActivity paused
2019-04-03 22:56:04: MainActivity destroyed
2019-04-03 22:56:04: MainActivity created

**Comment by msfjarvis** [comment]
It's a broken theme overlay, not an app bug. Uninstall and rebuild the overlay
