### ISSUE TITLE
Crash after getting lasteat android update

### ISSUE THREAD

**Issue by RenatoLopes771** [nicholaschum/substratum#205]
Please note: before I could apply themes (Altough they where not applied correctly), however there where no crashes.

Today, when my phone was downloading the new android security update (it didnt install it yet) it got crashing, what I did then was just restart to remove the themes, then apply the update, but it still kept crashing.

Heres the logs:

Build version: one thousand twenty two
Device: LM-Q710.FGN (mcv7a) [lge/mcv7a_lao_com/mcv7a:8.1.0/O11019/192471739eccf.FGN:user/release-keys]
ROM: 8.1.0 - Unknown
Theme system: OMS (andromeda)

Stack trace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{projekt.substratum/projekt.substratum.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2822)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2900)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4781)
	at android.app.ActivityThread.-wrap18(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1617)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6651)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:678)
	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:641)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:535)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
	at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:303)
	at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284)
	at projekt.substratum.MainActivity.onCreate(MainActivity.java:269)
	at android.app.Activity.performCreate(Activity.java:7028)
	at android.app.Activity.performCreate(Activity.java:7019)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2775)
	... 10 more

User actions:
2019-10-16 14:28:17: SplashScreenActivity created
2019-10-16 14:28:17: SplashScreenActivity resumed
2019-10-16 14:28:18: SplashScreenActivity paused
2019-10-16 14:28:18: MainActivity created
2019-10-16 14:28:18: MainActivity resumed
2019-10-16 14:28:19: SplashScreenActivity destroyed
2019-10-16 14:28:22: MainActivity paused
2019-10-16 14:29:09: LauncherActivity created
2019-10-16 14:29:09: SplashScreenActivity created
2019-10-16 14:29:09: SplashScreenActivity resumed
2019-10-16 14:29:09: LauncherActivity destroyed
2019-10-16 14:29:10: SplashScreenActivity paused
2019-10-16 14:29:10: MainActivity resumed
2019-10-16 14:29:10: SplashScreenActivity destroyed
2019-10-16 14:30:55: MainActivity paused
2019-10-16 14:30:55: MainActivity destroyed
2019-10-16 14:30:55: MainActivity created
2019-10-16 14:30:55: MainActivity resumed
2019-10-16 14:30:56: MainActivity paused
2019-10-16 14:30:56: MainActivity destroyed
2019-10-16 14:30:56: MainActivity created

**Comment by androidacy-user** [comment]
Did you remove any themes on substratum? `adb shell cmd overlay disable projekt.substratum<THEME>`

**Comment by underlineGalaxy** [comment]
@alexa-v2 OK how do I use these commands?

Moreover, how do I disable all themes? Substratum somehow made all the apps with themes applied unusuable (even itself, and thus I cant remove themes)

**Comment by androidacy-user** [comment]
@underlineGalaxy do you have TWRP?

**Comment by underlineGalaxy** [comment]
@alexa-v2 no

**Comment by androidacy-user** [comment]
@underlineGalaxy alright

Need adb set up

`adb shell cmd overlay list`

Look for projekt.substratum. in the name, add the last part to the next command 

`adb shell cmd overlay disable projekt.substratum<stuff from step one>`

This should allow you to get back to substratum. UNINSTALL NOT DISABLE all overlays. Reboot. Build again as desired, reboot, ebab reboot just to make sure
