### ISSUE TITLE
Error during "doInBackground" 

### ISSUE THREAD

**Issue by bleonard252** [nicholaschum/substratum#206]
<details><summary>Full log trace</summary>

```
Build version: one thousand twenty two
Device: LM-X410(FG) (cv3) [lge/cv3_lao_com/cv3:8.1.0/OPM1.171019.026/19339044070cd:user/release-keys]
ROM: 8.1.0 - Unknown
Theme system: OMS (andromeda)

Stack trace:
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ExceptionInInitializerError
	at projekt.substratum.tabs.OverlaysManager$CompileTask.doInBackground(OverlaysManager.java:1029)
	at projekt.substratum.tabs.OverlaysManager$CompileTask.doInBackground(OverlaysManager.java:325)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
Caused by: java.lang.NumberFormatException: s == null
	at java.lang.Integer.parseInt(Integer.java:570)
	at java.lang.Integer.parseInt(Integer.java:643)
	at projekt.substratum.common.References.getMagiskDirectory(References.java:254)
	at projekt.substratum.common.References.getSystemDir(References.java:250)
	at projekt.substratum.common.Internal.<clinit>(Internal.java:138)
	... 8 more


User actions:
2020-01-31 16:41:19: LauncherActivity created
2020-01-31 16:41:19: SplashScreenActivity created
2020-01-31 16:41:19: SplashScreenActivity resumed
2020-01-31 16:41:19: LauncherActivity destroyed
2020-01-31 16:41:19: SplashScreenActivity paused
2020-01-31 16:41:19: MainActivity created
2020-01-31 16:41:20: MainActivity resumed
2020-01-31 16:41:21: SplashScreenActivity destroyed
2020-01-31 16:41:27: MainActivity paused
2020-01-31 16:41:27: ThemeLaunchActivity created
2020-01-31 16:41:27: ThemeLaunchActivity resumed
2020-01-31 16:41:27: ThemeLaunchActivity paused
2020-01-31 16:41:27: InformationActivity created
2020-01-31 16:41:28: InformationActivity resumed
2020-01-31 16:41:29: ThemeLaunchActivity destroyed
```

</details>

**Comment by mafiaking007** [comment]
Same issue i am getting while compiling themes

Android version 8.1

**Comment by rafaelsgirao** [comment]
Exact same issue, exact same stacktrace. Refunding andromeda in the meanwhile.
